const dummyData1 = [
  {
    id: '2142141413asdasrt125asd',
    title: '같이 운동할 사람 구합니다 선착순 1명 빨리요!',
    personnel: '10명',
    phoneNumber: '123-123-1233',
    content: 'content Test',
    event: '배드민턴',
    region: '서울',
    createdAt: Date.now(),
  },
  {
    id: '@!#ssfs13514124easfgdsg',
    title: '같이 운동할 사람 구합니다 선착순 1명 빨리요 급합니다!',
    personnel: '10명',
    phoneNumber: '123-123-1233',
    content: 'content Test',
    event: '야구',
    region: '경기',
    createdAt: Date.now(),
  },
  {
    id: '!@%$!@%SGSDHFYF^WETSDFS',
    title: 'test3',
    personnel: '10명',
    phoneNumber: '123-123-1233',
    content: 'content Test',
    event: '농구',
    region: '인천',
    createdAt: Date.now(),
  },
  {
    id: '%&$YEWTGSDF!T@dgsdgfqt3252',
    title: 'test4',
    personnel: '10명',
    phoneNumber: '123-123-1233',
    content: 'content Test',
    event: '풋살',
    region: '대전',
    createdAt: Date.now(),
  },
  {
    id: '&%$&Y@SDGFSDdgwdsgtstgq32tqt',
    title: 'test5',
    personnel: '10명',
    phoneNumber: '123-123-1233',
    content: 'content Test',
    event: '골프',
    region: '대구',
    createdAt: Date.now(),
  },
  {
    id: '^&@#%#T!dsgsdtew5155tsrfsygh',
    title: 'test6',
    personnel: '10명',
    phoneNumber: '123-123-1233',
    content: 'content Test',
    event: '탁구',
    region: '부산',
    createdAt: Date.now(),
  },
  {
    id: '!#$%!5t13rtewsgdsgdsasgsdg346363y2',
    title: 'test7',
    personnel: '10명',
    phoneNumber: '123-123-1233',
    content: 'content Test',
    event: '축구',
    region: '강원',
    createdAt: Date.now(),
  },
  {
    id: '*$#&@#T@R@ASFASy726yqtsfdsd',
    title: 'test8',
    personnel: '10명',
    phoneNumber: '123-123-1233',
    content: 'content Test',
    event: '테니스',
    region: '광주',
    createdAt: Date.now(),
  },
  {
    id: '&%$U$YERGDFHHWty2y62tgdsfwt62^@%@343',
    title: 'test9',
    personnel: '10명',
    phoneNumber: '123-123-1233',
    content: 'content Test',
    event: '축구',
    region: '서울',
    createdAt: Date.now(),
  },
  {
    id: '^#$61gdfgh&&#yegg2^@^WGBER&R^EDGs',
    title: 'test10',
    personnel: '10명',
    phoneNumber: '123-123-1233',
    content: 'content Test',
    event: '배드민턴',
    region: '제주',
    createdAt: Date.now(),
  },
];

export default dummyData1;
