export const dummyData = [
  {
    id: '!@%TDVDSGFSFgasgagfas^!4rasdsaf',
    name: '다락원 체육공원',
    address: '서울특별시 도봉구 도봉동 1-1',
    phoneNumber: '123-123-123',
    imageUrl: 'asdasd',
    likeCount: 10,
  },
  {
    id: '!szczsC&sdfsdf*sadsafzv15r1w',
    name: '부산 시민 수영장',
    address: '부산',
    phoneNumber: '456',
    imageUrl: 'asdasd',
    likeCount: 20,
  },
  {
    id: '&@W#%@Dsadsadsafasf1241@sfsafsa',
    name: '풋살 아레나 광주점',
    address: '광주',
    phoneNumber: '789',
    imageUrl: 'asdasd',
    likeCount: 30,
  },
  {
    id: '!gg%asda2ASDsad6%^@#sadasdasd',
    name: '전주 공영 테니스장',
    address: '전주',
    phoneNumber: '012',
    imageUrl: 'asdasd',
    likeCount: 40,
  },
  {
    id: '!gg%asd512351$$T@^@DXVsasdd',
    name: '강원도 구민 체육관',
    address: '강원도',
    phoneNumber: '345',
    imageUrl: 'asdasd',
    likeCount: 50,
  },
];
